// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChLc4f9JOr5N6VmRam3fiQ_O4YzIonwUs',
    appId: '1:1029391786575:web:58db953b47a61b1844803a',
    messagingSenderId: '1029391786575',
    projectId: 'flutter-notificationcli',
    authDomain: 'flutter-notificationcli.firebaseapp.com',
    storageBucket: 'flutter-notificationcli.appspot.com',
    measurementId: 'G-NBT1ZPRQN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8T8HL_4VLxt2tCZhTiXapoPXBuf8L700',
    appId: '1:1029391786575:android:bd86831387985d4944803a',
    messagingSenderId: '1029391786575',
    projectId: 'flutter-notificationcli',
    storageBucket: 'flutter-notificationcli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKeWVqQUxnyc0QkVIHpyrW8hLItfhZ0Ys',
    appId: '1:1029391786575:ios:ee00fb47962dc48144803a',
    messagingSenderId: '1029391786575',
    projectId: 'flutter-notificationcli',
    storageBucket: 'flutter-notificationcli.appspot.com',
    iosBundleId: 'com.notifickkm.notifTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChLc4f9JOr5N6VmRam3fiQ_O4YzIonwUs',
    appId: '1:1029391786575:web:0fccd9b4de68a6b044803a',
    messagingSenderId: '1029391786575',
    projectId: 'flutter-notificationcli',
    authDomain: 'flutter-notificationcli.firebaseapp.com',
    storageBucket: 'flutter-notificationcli.appspot.com',
    measurementId: 'G-DH6PJVQGJB',
  );
}
